### PR TITLE
zh-Hans Localization

### PR DESCRIPTION
**Pull request by urgiv**
fix NPC shop
add zh-Hans
adjust en-us
"SpawnRateDisplay: ~{0} {^0:spawn;spawns} per second", this line cause UI disappearance bug, so I rewrite it to "{0} spawns per second"

### CODE REVIEW

**Review by BlockCrusader — APPROVED** [review]
Thanks for helping localize more of my mods!
The error with SpawnRateDisplay is actually already fixed, I must have forgot to push the change to GitHub. My solution splits that translation key into two seperate entries, so you'll have to make a quick update to the zh-Hans file to accommodate.

**Comment by BlockCrusader** [comment]
The mod is now updated with this localization on Steam Workshop!
By the way, if you have a username other than the one you use here (Ex: The one you use on Steam) that you would prefer be used when I credit you (Which I do, in changelogs and a localization section of descriptions), please let me know! :)

**Comment by urgiv** [comment]
For workshop title and description:
https://github.com/urgiv/zh-Hans-localization-files-for-1.4.4-mods/blob/4f7268e0b373823fd08b22f1b0f585a4badfca2b/workshop%20Title%20%26%20Description%20here/Block's%20Info%20Accessories/SimplifiedChinese_workshop.txt
Just the name "urgiv" is fine enough.

**Comment by BlockCrusader** [comment]
Got it. Description now has the localization added

**Pull request merged**
